import { NextResponse } from "next/server";
import { z } from "zod";
import { isCloverCheckoutConfigured } from "@/integrations/clover/config";
import { getMenuItems } from "@/services/menu.service";
import {
  createCloverOrder,
  addCloverLineItem,
  addCloverModification,
  getCloverOrderDetails,
} from "@/integrations/clover/orders";
import { payCloverOrder } from "@/integrations/clover/payments";
import { saveOrder, getOrder, updateOrder } from "@/lib/db";
import type { Order, OrderStatus, PaymentStatus } from "@/types";

const placeOrderSchema = z.object({
  checkoutReference: z.string().uuid(), // Unique ID generated by client (acts as order.id)
  items: z
    .array(
      z.object({
        menuItemId: z.string(),
        quantity: z.number().int().min(1),
        selectedModifiers: z.array(
          z.object({
            modifierId: z.string(),
          })
        ),
      })
    )
    .min(1),
  orderType: z.enum(["pickup", "delivery"]),
  customer: z.object({
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    email: z.string().email(),
    phone: z.string().min(10),
  }),
  deliveryAddress: z
    .object({
      street: z.string().min(1),
      apartment: z.string().optional(),
      city: z.string().min(1),
      state: z.string().min(2),
      zip: z.string().min(5),
    })
    .optional(),
  notes: z.string().max(500).optional(),
  tipAmount: z.number().min(0),
  paymentToken: z.string().min(1), // Clover token from iframe tokenizer
});

// In-memory rate limiting store (lasts as long as server instance is warm)
const rateLimitMap = new Map<string, number>();

export async function POST(req: Request) {
  try {
    // 1. Rate Limiting Check
    const ip = req.headers.get("x-forwarded-for") || "anonymous";
    const now = Date.now();
    const lastRequestTime = rateLimitMap.get(ip);
    if (lastRequestTime && now - lastRequestTime < 2000) {
      // 2-second rate limit
      return NextResponse.json(
        { error: "Too many requests. Please wait a moment." },
        { status: 429 }
      );
    }
    rateLimitMap.set(ip, now);

    // 2. Safety Check for Live Checkout
    if (process.env.NEXT_PUBLIC_ENABLE_LIVE_CHECKOUT !== "true") {
      return NextResponse.json(
        {
          error: "Live checkout is disabled.",
          code: "CHECKOUT_DISABLED",
        },
        { status: 403 }
      );
    }

    // 2.5. Configuration Check
    if (!isCloverCheckoutConfigured()) {
      return NextResponse.json(
        {
          error: "Clover online ordering is currently unavailable.",
          code: "CLOVER_NOT_CONFIGURED",
        },
        { status: 503 }
      );
    }

    // 3. Request Validation
    const body = await req.json();
    const result = placeOrderSchema.safeParse(body);
    if (!result.success) {
      return NextResponse.json(
        { error: "Invalid request data", details: result.error.format() },
        { status: 400 }
      );
    }

    const {
      checkoutReference,
      items: cartItems,
      orderType,
      customer,
      deliveryAddress,
      notes,
      tipAmount,
      paymentToken,
    } = result.data;

    // 4. Idempotency Check
    const existingOrder = await getOrder(checkoutReference);
    if (existingOrder) {
      console.log(
        `[Idempotency] Found existing order for reference ${checkoutReference}. Status: ${existingOrder.status}`
      );
      if (existingOrder.paymentStatus === "PAID") {
        return NextResponse.json({
          success: true,
          orderId: existingOrder.id,
          orderNumber: existingOrder.orderNumber,
        });
      }
      if (existingOrder.status === "PAYMENT_PROCESSING") {
        return NextResponse.json(
          { error: "Order is already processing payment." },
          { status: 409 }
        );
      }
    }

    // 5. Resolve local menu items and verify availability/mapping
    const { items: allMenuItems } = await getMenuItems();
    const verifiedItemsToCreate = [];
    const dbOrderItems = [];

    for (const cartItem of cartItems) {
      const menuItem = allMenuItems.find((i) => i.id === cartItem.menuItemId);
      if (!menuItem) {
        return NextResponse.json(
          { error: `Item not found in menu: ${cartItem.menuItemId}` },
          { status: 400 }
        );
      }

      if (!menuItem.available) {
        return NextResponse.json(
          { error: `Item is currently unavailable: ${menuItem.name}` },
          { status: 400 }
        );
      }

      const cloverItemId = menuItem.cloverItemId;
      if (!cloverItemId) {
        return NextResponse.json(
          { error: `Item not mapped to Clover: ${menuItem.name}` },
          { status: 400 }
        );
      }

      const resolvedModifierIds: string[] = [];
      const dbModifiers = [];

      for (const selMod of cartItem.selectedModifiers) {
        let foundMod = null;
        if (menuItem.modifierGroups) {
          for (const group of menuItem.modifierGroups) {
            const mod = group.modifiers.find((m) => m.id === selMod.modifierId);
            if (mod) {
              foundMod = mod;
              break;
            }
          }
        }

        if (!foundMod || !foundMod.cloverModifierId) {
          return NextResponse.json(
            { error: `Modifier not mapped: ${selMod.modifierId}` },
            { status: 400 }
          );
        }

        resolvedModifierIds.push(foundMod.cloverModifierId);
        dbModifiers.push({
          modifierId: foundMod.id,
          cloverModifierId: foundMod.cloverModifierId,
          name: foundMod.name,
          additionalPrice: foundMod.additionalPrice,
        });
      }

      verifiedItemsToCreate.push({
        cloverItemId,
        quantity: cartItem.quantity,
        cloverModifierIds: resolvedModifierIds,
      });

      dbOrderItems.push({
        id: "", // filled by database save
        orderId: checkoutReference,
        menuItemId: menuItem.id,
        cloverItemId,
        name: menuItem.name,
        price: menuItem.price,
        quantity: cartItem.quantity,
        modifiers: dbModifiers,
      });
    }

    // 6. Generate order numbers and set statuses
    const orderNumber = `OD-${Date.now().toString().slice(-6)}-${Math.random()
      .toString(36)
      .substring(2, 5)
      .toUpperCase()}`;

    // Construct customer note for Clover Ticket printing
    const customerInfoStr = `${customer.firstName} ${customer.lastName} (${customer.phone})`;
    const fulfillmentStr =
      orderType === "delivery" && deliveryAddress
        ? `Delivery: ${deliveryAddress.street}, ${deliveryAddress.city}, ${deliveryAddress.state} ${deliveryAddress.zip}`
        : "Pickup";
    const cloverNote = `[Website Order] #${orderNumber}\nCustomer: ${customerInfoStr}\nFulfillment: ${fulfillmentStr}\nNotes: ${
      notes || "None"
    }`;

    // 7. Create a Clover V3 Order
    console.log(`[Place Order] Creating Clover order for ${orderNumber}...`);
    const cloverOrder = await createCloverOrder(orderType, cloverNote);
    const cloverOrderId = cloverOrder.id;

    // 8. Add Items and Modifiers to Clover Order
    console.log(`[Place Order] Adding items to Clover order ${cloverOrderId}...`);
    for (const item of verifiedItemsToCreate) {
      for (let q = 0; q < item.quantity; q++) {
        const lineItem = await addCloverLineItem(cloverOrderId, item.cloverItemId);
        for (const modId of item.cloverModifierIds) {
          await addCloverModification(cloverOrderId, lineItem.id, modId);
        }
      }
    }

    // 9. Fetch authoritative calculated Clover totals
    const details = await getCloverOrderDetails(cloverOrderId);
    let computedSubtotal = 0;
    if (details.lineItems?.elements) {
      for (const li of details.lineItems.elements) {
        computedSubtotal += li.price ?? 0;
        if (li.modifications?.elements) {
          for (const mod of li.modifications.elements) {
            computedSubtotal += mod.amount ?? 0;
          }
        }
      }
    }
    const orderTotalCents = details.total ?? 0;
    const computedTax = Math.max(0, orderTotalCents - computedSubtotal);

    const tipCents = Math.round(tipAmount * 100);
    const finalTotalCents = orderTotalCents + tipCents;

    // 10. Write DRAFT order details to local database
    const localOrder: Order = {
      id: checkoutReference,
      orderNumber,
      customerName: `${customer.firstName} ${customer.lastName}`,
      customerEmail: customer.email,
      customerPhone: customer.phone,
      orderType,
      status: "VALIDATING" as OrderStatus,
      paymentStatus: "UNPAID" as PaymentStatus,
      subtotalCents: computedSubtotal,
      taxCents: computedTax,
      tipCents,
      deliveryFeeCents: 0,
      totalCents: finalTotalCents,
      cloverOrderId,
      notes: notes || "",
      pickupTime: "", // optional/scheduled
      deliveryAddress:
        orderType === "delivery" && deliveryAddress ? deliveryAddress : undefined,
      items: dbOrderItems,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await saveOrder(localOrder);

    // 11. Process secure payment through Clover Ecommerce (SCL)
    console.log(
      `[Place Order] Attempting Clover SCL payment for order ${cloverOrderId} amount ${finalTotalCents} cents...`
    );
    await updateOrder(checkoutReference, { status: "PAYMENT_PROCESSING" as OrderStatus });

    try {
      const paymentRes = await payCloverOrder(cloverOrderId, paymentToken);

      if (paymentRes.status === "succeeded") {
        console.log(
          `[Place Order] Payment succeeded for order ${orderNumber}. Clover Payment ID: ${paymentRes.id}`
        );

        // 12. Mark order as PAID upon confirmed approval
        await updateOrder(checkoutReference, {
          status: "PAID" as OrderStatus,
          paymentStatus: "PAID" as PaymentStatus,
          cloverPaymentId: paymentRes.id,
        });

        return NextResponse.json({
          success: true,
          orderId: checkoutReference,
          orderNumber,
        });
      } else {
        console.warn(
          `[Place Order] Payment status: ${paymentRes.status}. Code: ${paymentRes.failure_code}. Msg: ${paymentRes.failure_message}`
        );

        await updateOrder(checkoutReference, {
          status: "PAYMENT_FAILED" as OrderStatus,
          paymentStatus: "FAILED" as PaymentStatus,
        });

        return NextResponse.json(
          {
            error: paymentRes.failure_message || "Payment declined.",
            code: paymentRes.failure_code || "PAYMENT_DECLINED",
          },
          { status: 402 }
        );
      }
    } catch (payErr: unknown) {
      console.error(`[Place Order] Payment transaction exception:`, payErr);

      await updateOrder(checkoutReference, {
        status: "PAYMENT_FAILED" as OrderStatus,
        paymentStatus: "FAILED" as PaymentStatus,
      });

      return NextResponse.json(
        {
          error: "Credit card transaction failed. Please check details and try again.",
          code: "PAYMENT_TRANSACTION_FAILED",
        },
        { status: 402 }
      );
    }
  } catch (err: unknown) {
    console.error("[Place Order Error]:", err);
    return NextResponse.json(
      {
        error:
          err instanceof Error
            ? err.message
            : "An unexpected error occurred while placing order.",
      },
      { status: 500 }
    );
  }
}
